# Generated by Django 3.1.7 on 2021-03-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_story_is_optimized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='is_optimized',
        ),
    ]
